### ISSUE TITLE
Error while decoding QSPI

### ISSUE THREAD

**Issue by aignacio** [adafruit/Logic2-SPIFlash#5]
Hi,

I'm trying to decode using your plugin but it seems to show some error when it tries to parse the raw data....can you check the following signals attached?

[qspi.sal.zip](https://github.com/adafruit/Logic2-SPIFlash/files/7039473/qspi.sal.zip)

**Comment by tannewt** [comment]
I don't have time to debug your signal. I'm happy to merge a fix that you find but I don't support this code myself. It's open as a starting point for others.
