### ISSUE TITLE
Extension not working

### ISSUE THREAD

**Issue by picatostas** [adafruit/Logic2-SPIFlash#7]
I am using Logic 8 Original from Saleae, Logic 2.3.59 on Windows 11
I installed the extension from the Extension manager within Logic 2.3.59

I followed the instructions on the readme and I cannot get the SPI Flash parser to work.

This is a capture were I do a WREN and a WR and It doesn't get parsed
![image](https://user-images.githubusercontent.com/36212945/189734662-b010e22f-83e7-416d-ba20-e937c2fdd70a.png)
These are the SPI settings
![image](https://user-images.githubusercontent.com/36212945/189734709-eca27c38-52a1-4d96-bf8b-ae21501b28c0.png)
And these are the SPI Flash settings
![image](https://user-images.githubusercontent.com/36212945/189734836-d4a1a804-1d09-4e09-ac6a-c935449a2b2a.png)

What am I missing ?

**Comment by tannewt** [comment]
It may be broken. I think most folks use the simple parallel input to debug QSPI flashes.

**Comment by otti** [comment]
Hi @picatostas,

maybe a little bit too late for you but perhaps helpful for others ;-)

SPI Flash Chips are working fine with this decoder.
You have to select an "Enable" signal (CS) in the configuration of the SPI decoder.

Perhaps this is only valid for my Flash (IS25WP016D), but ...
- The command 0x06 (Write enable) is a one byte command.
- The command 0x02 (Page Program) needs three additional address bytes before sending the data
![image](https://github.com/adafruit/Logic2-SPIFlash/assets/3578456/541e6479-1834-4918-b2ad-3fb8407e6c09)
